#! /usr/bin/env bash
# initialize virtualenv if missing
# and start the program

program_dir=$(dirname $0)

if [[ -z "$program_dir" ]]; then
    program_dir="."
fi

program_abs_path=$(realpath $program_dir)

if [[ "$(pwd)" != "$program_abs_path" ]]; then
    cd $program_abs_path
fi

initialized_flag=0

if [[ ! -d "venv" ]]; then
    echo "initializing virtualenv"
    python3 -m venv venv
else
    initialized_flag=1
fi

source venv/bin/activate
if [[ $initialized_flag -eq 0 ]]; then
    echo "installing dependencies into virtualenv"
    pip install -r requirements.txt
fi
exec python3 obamawatcher.py

